services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icp-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
