# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x1f\n\rFeatureVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"X\n\x0ePredictRequest\x12\x0f\n\x05image\x18\x01 \x01(\x0cH\x00\x12,\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x18.inference.FeatureVectorH\x00\x42\x07\n\x05input\".\n\x0fPredictResponse\x12\t\n\x01y\x18\x01 \x01(\x02\x12\x10\n\x08infer_ms\x18\x02 \x01(\x01\x32M\n\tInference\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATUREVECTOR']._serialized_start=30
  _globals['_FEATUREVECTOR']._serialized_end=61
  _globals['_PREDICTREQUEST']._serialized_start=63
  _globals['_PREDICTREQUEST']._serialized_end=151
  _globals['_PREDICTRESPONSE']._serialized_start=153
  _globals['_PREDICTRESPONSE']._serialized_end=199
  _globals['_INFERENCE']._serialized_start=201
  _globals['_INFERENCE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
